# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set environment variables to prevent Python from writing pyc files to disk and to ensure stdout/stderr is unbuffered
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies for pdf2image and other libraries
RUN apt-get update && \
    apt-get install -y poppler-utils libglib2.0-0 libsm6 libxrender1 libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install uvicorn fastapi pdf2image
RUN apt-get update
RUN apt-get install libgomp1 
RUN apt-get install ffmpeg libsm6 libxext6  -y

# Copy the rest of the application code to the working directory
COPY ./* /app/

# Expose port 8000 for the FastAPI application
EXPOSE 8000

# Run the application using uvicorn
CMD ["uvicorn", "fastapi_test:app", "--host", "0.0.0.0=", "--port", "8000"] 